# Advanced: a fixed, manually-authored channel plan.
# A channel plan is normally generated by the controller's RF optimization; only
# manage this resource when you intend to pin channel assignments explicitly.
resource "unifi_channel_plan" "fixed" {
  radio_table = [
    {
      device_mac    = "aa:bb:cc:dd:ee:ff"
      name          = "rai0"
      channel       = "36"
      tx_power      = "auto"
      tx_power_mode = "auto"
      width         = 80
    },
    {
      device_mac    = "aa:bb:cc:dd:ee:ff"
      name          = "ra0"
      channel       = "6"
      tx_power      = "auto"
      tx_power_mode = "auto"
      width         = 20
    },
  ]
}
